int pow(int base, int exponent);
int strcmp(char* a, char* b);
int  strlen     ( char * s );
void substr	( char s[20], char target[20], int start, int len);
void itoa	( int x, char str[], int d);
void ftoa       ( float n, char* res, int afterpoint );
void reverse	( char *s );
int ls(char input[20], int readcontent);
int checkcat(char input[20]);
void cat(char input[20]);
void print_welcome();
void shell(char* input);
